### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by simonherbert** [prometheus-community/avalanche#24]
The public docker image `quay.io/freshtracks.io/avalanche` lacks an ARM version.
`standard_init_linux.go:228: exec user process caused: exec format error`
I just built the project from `master` on an ARM machine. Works flawlessly.

**Comment by simonpasquier** [comment]
The main tag should have be ARM-compatible now.
https://quay.io/repository/prometheuscommunity/avalanche?tab=tags
