### ISSUE TITLE
add option to run avalanche without refreshing values (e.g. let intervals take a value of zero)

### ISSUE THREAD

**Issue by sed-i** [prometheus-community/avalanche#27]
I would like to run avalanche without it ever refreshing `series_id` nor `__name__ label`.
One way to specify this is with an interval value of zero.

```
$ ./cmd --series-interval=0 --metric-interval=0
panic: non-positive interval for NewTicker

goroutine 1 [running]:
time.NewTicker(0x0, 0xc0001aa500)
        /usr/lib/go-1.13/src/time/tick.go:23 +0x147
github.com/open-fresh/avalanche/metrics.RunMetrics(0xa, 0xa, 0xa, 0x5, 0x5, 0x1e, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/go/src/github.com/open-fresh/avalanche/metrics/serve.go:97 +0x64e
main.main()
        /home/ubuntu/go/src/github.com/open-fresh/avalanche/cmd/avalanche.go:44 +0x1a8
```

https://github.com/open-fresh/avalanche/blob/0c1c64c97f6dc5630ae5c057821cc8e08a12922b/cmd/avalanche.go#L24-L25

https://github.com/open-fresh/avalanche/blob/0c1c64c97f6dc5630ae5c057821cc8e08a12922b/metrics/serve.go#L97-L98

**Comment by bwplotka** [comment]
Fixed in https://github.com/prometheus-community/avalanche/pull/80
