### ISSUE TITLE
Latest main is not sending metrics compared to v0.5

### ISSUE THREAD

**Issue by wiardvanrij** [prometheus-community/avalanche#86]
Hi folks, maybe I'm missing something but trying out the main branch, I cannot get it to send metrics to our remote write endpoint. Figured to create an issue for it.

Example usage:
```
docker run quay.io/prometheuscommunity/avalanche:main --remote-url=redacted --remote-tenant=redacted   --remote-requests-count=1000 --remote-tenant-header=redacted --gauge-metric-count=200
Emulate Docker CLI using podman. 
16:47:15 avalanche.go:84: initializing avalanche...
16:47:15 write.go:128: Sending:  0 timeseries, 1000 samples, 2000 timeseries per request, 100ms delay between requests
```

Maybe I'm missing a flag, but I'm unsure which. 

Using the 0.5.0 version works fine:

```
 Sending:  5000 timeseries, 1000 samples, 2000 timeseries per request, 100ms delay between requests
```

**Comment by bwplotka** [comment]
Yup, we are doing some development on main, potentially impacting things, thanks for reporting!
 
 The ` 5000 timeseries,` vs `0 timeseries` is interesting... let me investigate a bit.
